### ISSUE TITLE
installation fails with Invalid cross-device link error

### ISSUE THREAD

**Issue by msz59** [jobovy/mwdust#10]
If DUST_DIR and git-cloned "mwdust" are on different partitions, installation by
`cd mwdust`
`python setup.py install`
fails reporting:
> [...]
> Downloading Sale et al. (2014) dust maps ...
> [...]
> 2018-09-15 11:09:54 (9.21 MB/s) - ‘/home/[...]/MWDUST/sale14/Amap.tar.gz’ saved [111829141/111829141]
> 
> Amap.dat
> ReadMe
> Traceback (most recent call last):
>   File "setup.py", line 265, in <module>
>     'Amap.dat'))
> OSError: [Errno 18] Invalid cross-device link

Python 2.7.15rc1 on Ubuntu 18.04 machine.
regards, Michal

**Comment by jobovy** [comment]
Thanks for reporting. I pushed a fix to ``master``, please re-open if that doesn't solve this issue.
