### ISSUE TITLE
ftp://ftp.oato.inaf.it/astrometria/extinction/data-for.tar.gz unavailable for download

### ISSUE THREAD

**Issue by sousasag** [jobovy/mwdust#14]
Hi,

During the installation of this module, the Drimmel data which is given as an example for the usage is not accessible right now (ftp://ftp.oato.inaf.it/astrometria/extinction/data-for.tar.gz).

I was able to skip this download in the setup, but maybe you can add this file to the repository as you say it does not occupy much space??

**Comment by jobovy** [comment]
Hi Sergio,

Yes, the file seems to have been temporarily down, but it looks like it's back up now!

**Comment by sousasag** [comment]
Indeed. Now is available. Great. Thanks.
