### ISSUE TITLE
QUESTION about mwdust.Combined19

### ISSUE THREAD

**Issue by barbierimauro** [jobovy/mwdust#20]
Hi all,
I would like to use this package inside one of my code for calculating the extinction of a number of stars distributed in all sky.
My preference is to use the maps from mwdust.Green19, however they do not include some part of the sky.
I would like to ask what is the footprint of mwdust.Combined19, does it cover all the sky ? My feeling is that it will have the same footprint of mwdust.Green19.
If this is the case, there is some alternative map that cover all sky using as primary source mwdust.Green19, and that fill the missing parts with other maps ?
Thanks in advance

**Comment by jobovy** [comment]
Yes, `mwdust.Combined19`, that's the point of the combined maps. [This paper](https://ui.adsabs.harvard.edu/abs/2016ApJ...818..130B/abstract) explains how the combined maps are constructed, `mwdust.Combined19` is just an update of `mwdust.Combined15` swapping `Green19` for `Green15`.

**Comment by barbierimauro** [comment]
Many thanks for the clarification.
