### ISSUE TITLE
Cannot install with pip

### ISSUE THREAD

**Issue by astrobatty** [jobovy/mwdust#40]
I was trying to install `mwdust` with pip, but it failed with an error that says it can't find a C header file. After cloning the repo and using `pip install .` it worked. There might be a problem with the path of included directories.

**Comment by jobovy** [comment]
Could you send the actual error?

**Comment by astrobatty** [comment]
Of course.

```
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/batty/opt/miniconda3/envs/test/include -arch x86_64 -I/Users/batty/opt/miniconda3/envs/test/include -arch x86_64 -Imwdust/util/SFD_CodeC -I/Users/batty/opt/miniconda3/envs/test/include/python3.7m -c mwdust/util/SFD_CodeC/subs_asciifile.c -o build/temp.macosx-10.9-x86_64-cpython-37/mwdust/util/SFD_CodeC/subs_asciifile.o -DLITTLE_ENDIAN
      mwdust/util/SFD_CodeC/subs_asciifile.c:4:10: fatal error: subs_memory.h: No such file or directory
          4 | #include "subs_memory.h"
            |          ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/Applications/mesasdk/bin/gcc' failed with exit code 1
      [end of output]
```

Some other details:
OS: OS X 12.5 (Monterey)
Python: 3.7.13 Anaconda
gcc: 13.1.0

**Comment by jobovy** [comment]
Yeah, looks like the relevant file is missing. I'm surprised this hasn't come up before, because I think it must have always been missing! 

Note that we actually provide binary wheels on PyPI, but these aren't being installed in your case because you are still on Python 3.7 (which is no longer supported).

**Comment by jobovy** [comment]
I think this should be resolved by the changes that I made in #41 (seems like the main issue was that the `MANIFEST.IN` file should have been called `MANIFEST.in`), but I'll have to release a new version to be sure.

For now, you should just be able to pip install the `main` branch as
```
pip install git+https://github.com/jobovy/mwdust.git
```

**Comment by jobovy** [comment]
New version on PyPI now and this does seem to now contain the correct files.

**Comment by astrobatty** [comment]
It does and works now.
