### ISSUE TITLE
Install: SUDO_USER environment variable doesnt exist

### ISSUE THREAD

**Issue by johnh2o2** [jobovy/mwdust#5]
I've included the bash history of my attempt to install via instructions in the README, however I'm running into a problem: the environment variable `SUDO_USER` does not exist on my machine, but `USER` does. Simply replacing all instances of `SUDO_USER` with `USER` in `setup.py` fixes the problem for me. It may be useful to have `setup.py` check whether or not `SUDO_USER` is a valid environment variable and either throw an exception specific to that problem.

### System:
* **Device** : MacBook Pro (15-inch, Mid 2012)
* **OS**: macOS sierra
* **CPU** : 2.6 GHz Intel Core i7

### Log:
```
$ python --version
Python 2.7.12 :: Anaconda 4.2.0 (x86_64)
$ git clone https://github.com/jobovy/mwdust.git
Cloning into 'mwdust'...
remote: Counting objects: 432, done.
remote: Total 432 (delta 0), reused 0 (delta 0), pack-reused 432
Receiving objects: 100% (432/432), 97.67 KiB | 0 bytes/s, done.
Resolving deltas: 100% (252/252), done.
$ cd mwdust
$ mkdir DUST_DIR
$ export pathname="${PWD}/DUST_DIR"
$ echo $pathname
/Users/jah5/Documents/installs/mwdust/DUST_DIR
$ echo "export DUST_DIR=\"${pathname}\"" >> ~/.bashrc
$ . ~/.bashrc
$ echo $DUST_DIR
/Users/jah5/Documents/installs/mwdust/DUST_DIR
$ mkdir ../mwdust_install
$ python setup.py install --prefix=../mwdust_install
Traceback (most recent call last):
  File "setup.py", line 51, in <module>
    'maps')])
  File "/Users/jah5/anaconda2/lib/python2.7/subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/Users/jah5/anaconda2/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/Users/jah5/anaconda2/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/Users/jah5/anaconda2/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```

In addition, I found that by manually setting the installation directory a la `python setup.py install --prefix=...` causes Python to complain that:

```
running install
Checking .pth file support in ../mwdust_install/lib/python2.7/site-packages/
/Users/jah5/anaconda2/bin/python -E -c pass
TEST FAILED: ../mwdust_install/lib/python2.7/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    ../mwdust_install/lib/python2.7/site-packages/

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations


Please make the appropriate changes for your system and try again.
```

I may be misusing the `--prefix` option, but I found that simply installing as usual (`python setup.py install`) worked without a problem, and on systems where permissions are an issue, I believe that specifying the `--user` option (`python setup.py install --user`) should avoid the problems I ran into when using the `--prefix` option.

**Comment by jobovy** [comment]
``SUDO_USER`` is only defined *when* you install using ``sudo``, but because the ``setup.py`` file assumes that your username is ``$SUDO_USER`` (to change some permissions when downloading data) you have to define ``SUDO_USER`` if you are not installing as ``sudo``, e.g.
```
export SUDO_USER=jah5
python setup.py install
```

I think the issue with your ``--prefix=...`` installation is that you are trying to install to a directory that is not on your python path. If  ``--user`` works for you then just stick with that.

**Comment by johnh2o2** [comment]
Hi Jo,

Thanks for the response -- I took a look at your README again and saw that you do indeed mention the necessity of defining the `SUDO_USER` environment variable, so this is entirely my mistake!

**Comment by jobovy** [comment]
No problem, I had to read through the README five times to remember what I meant by that statement!
