### ISSUE TITLE
Installation on mac

### ISSUE THREAD

**Issue by dr-mcsmith** [jobovy/mwdust#9]
Hi - I'm using Python 3 installed with miniconda on a mac (osx 10.13.6). I am unable to install mwdust as I get the following error:

> \> sudo -E python3 setup.py install
...
/private/var/folders/tl/_5z6xmqd5_x4y0ljl2txp3740000gn/T/easy_install-cqf3s9qs/healpy-1.12.4/healpixsubmodule/src/cxx/autotools/cxxsupport/datatypes.h:74:10: fatal error: 
      'cstdint' file not found
#include <cstdint>
...

Google indicates that the problem may be some Clang/GCC issue - my Python installation uses GCC4.2.1, which it seems doesn't include cstdint. For example if I open Python3 it says:

> Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin

My Xcode is up to date. Attached is the full installation report.

Cheers,

Martin
[mwdust_install.txt](https://github.com/jobovy/mwdust/files/2375567/mwdust_install.txt)

**Comment by jobovy** [comment]
This looks like an issue with installing ``healpy``, not anything to do with ``mwdust`` itself. ``healpy`` is a pain to install, but since you're using Anaconda, try first installing it from that
```
conda install -c conda-forge healpy
```
and then installing ``mwdust``.

**Comment by dr-mcsmith** [comment]
Hey Jo - thanks. That worked perfectly. Apologies for not figuring that out myself...
